{% set name = "naima" %}
{% set python_min = "3.10" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e86de6d9114ae9c683b3ae311451d1de6e9d9574f923b7b133a86d1dac7e39b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - astropy-base >=6.1
    - emcee
    - corner
    - matplotlib-base >=1.4.0
    - scipy
    - h5py
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - naima

about:
  home: http://github.com/zblz/naima
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Derivation of non-thermal particle distributions through MCMC spectral fitting
  description: |
    naima is a Python package for computation of non-thermal radiation from
    relativistic particle populations. It includes tools to perform MCMC
    fitting of radiative models to X-ray, GeV, and TeV spectra using emcee, an
    affine-invariant ensemble sampler for Markov Chain Monte Carlo.
  doc_url: https://naima.readthedocs.io
  dev_url: http://github.com/zblz/naima

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - zblz
