{% set name = "naima" %}

{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08a3f9775c6322f0d89eb83134ef03b0e1cd46a1300439f3bbff4f41f315cfd2

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base >=4.3
    - emcee ~=3.1
    - corner
    - matplotlib-base
    - scipy
    - h5py
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - naima

about:
  home: http://github.com/zblz/naima
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Derivation of non-thermal particle distributions through MCMC spectral fitting
  description: |
    naima is a Python package for computation of non-thermal radiation from
    relativistic particle populations. It includes tools to perform MCMC
    fitting of radiative models to X-ray, GeV, and TeV spectra using emcee, an
    affine-invariant ensemble sampler for Markov Chain Monte Carlo.
  doc_url: https://naima.readthedocs.io
  dev_url: http://github.com/zblz/naima

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - zblz
