{% set name = "naima" %}

{% set version = "0.8.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "1ef4125ff463ca4dd934debc87a21503c405257ea3a6c8b91b9c69e268460da4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt
  skip: true  # [osx and py35]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - astropy >=1.0.2
    - emcee >=2.2.0
    - corner
    - matplotlib
    - scipy
    - h5py
    - pyyaml

test:
  imports:
    - naima

about:
  home: http://github.com/zblz/naima
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Derivation of non-thermal particle distributions through MCMC spectral fitting
  description: |
    naima is a Python package for computation of non-thermal radiation from
    relativistic particle populations. It includes tools to perform MCMC
    fitting of radiative models to X-ray, GeV, and TeV spectra using emcee, an
    affine-invariant ensemble sampler for Markov Chain Monte Carlo.
  doc_url: https://naima.readthedocs.io
  dev_url: http://github.com/zblz/naima

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - zblz
