{% set name = "naima" %}

{% set version = "0.9.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'af5db939ded57ba4136e35fb987da106d0e195445da7752870b9b72911fdc342'

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py2k]

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python
    - astropy >=1.0.2
    - emcee >=2.2.0,<3.0
    - corner
    - matplotlib-base
    - scipy
    - h5py
    - pyyaml

test:
  imports:
    - naima

about:
  home: http://github.com/zblz/naima
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Derivation of non-thermal particle distributions through MCMC spectral fitting
  description: |
    naima is a Python package for computation of non-thermal radiation from
    relativistic particle populations. It includes tools to perform MCMC
    fitting of radiative models to X-ray, GeV, and TeV spectra using emcee, an
    affine-invariant ensemble sampler for Markov Chain Monte Carlo.
  doc_url: https://naima.readthedocs.io
  dev_url: http://github.com/zblz/naima

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - zblz
