{% set name = "naima" %}
{% set python_min = "3.11" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c9abb544ee547db34d9678b16641c48fb36d9acf52871952ca133b7c98fe2ae8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - astropy-base >=6.1
    - emcee >=3.0
    - corner >=2.0
    - matplotlib-base >=3.10.0
    - scipy >=1.15.3
    - h5py >=3.14.0
    - pyyaml >=6.0.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - naima

about:
  home: http://github.com/zblz/naima
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Derivation of non-thermal particle distributions through MCMC spectral fitting
  description: |
    naima is a Python package for computation of non-thermal radiation from
    relativistic particle populations. It includes tools to perform MCMC
    fitting of radiative models to X-ray, GeV, and TeV spectra using emcee, an
    affine-invariant ensemble sampler for Markov Chain Monte Carlo.
  doc_url: https://naima.readthedocs.io
  dev_url: http://github.com/zblz/naima

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - zblz
