appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nysD3dc/RRiPau45A1j8yPemd1W40a2fCAw/VUTOamGPCX1LP0lrYCxXYWOeH1FOqvU8v5GLwzKGExG8z9m1/6QTIf4g/L4/QH4ABaOQ3e5BvmHoX7+TNLY6OuhInpNcCt6XBdkAhvHliuPej8aojIlGsKUktvo1QKRnLLTSij0gG+AQvCgJ2oEmFaEO99ivJd96SDo9O5mF7YHLFQnM5XPITDw3tIBHbFuL+3hQq8MkZrNbcL1OyGIDQngcvzawnpCd/O0JTX86jBjNutlh5i4cspOZff1sJGfj+0B8ubSsl7X2Sq49HcAwgDyHguTrbqX3R5tFRV//Dn09XVsORH7wc0wjrX+K/VEk0OnbMPdHwvcAI7XM3dJeXiFy/RsswrO0CcTz+nwJ07aWDDYuxyL1k0PFqXli4a7cUozsrGpeQzYh2AwHfaDrnqmxXhil1kldAZB8kWvSiOZyrXH4MJHJ3sPBCBEK57PruNBrNuhwW5l/x8QmxnItd0VATgfnBzm2dupa4eKdzjS5PUvvbL6OfWNEycQsOs+O53kgvml7m0nGCmA6hhh7Vg9CX7BHrjjR1IkX8iXQOoRPyAJJD+FwkCwMAV9IcA49BhEZ7hqz6/ihhojrC8RWSoECKfr60LW4Z3pAQatUHrkKsTqMpQjwM46TVByYgRprMrIZy8s=}
provider:
  win: azure
